//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storify.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public Story()
        {
            this.User_Story_Group = new HashSet<User_Story_Group>();
        }
    
        public int StoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public System.DateTimeOffset PostedOn { get; set; }
    
        public virtual ICollection<User_Story_Group> User_Story_Group { get; set; }
    }
}
