//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storify.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Story_Group
    {
        public int UserStoryGroupId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> StoryId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Story Story { get; set; }
        public virtual User User { get; set; }
    }
}
